// Fish of the day — 115 entries (local list, no API). Edit to add more.
window.FISH_DATABASE = [
  { name: "Red Drum", fact: "Texas state saltwater fish — common in Galveston Bay." },
  { name: "Alligator Gar", fact: "Ancient armored fish found in Houston-area bayous." },
  { name: "Clownfish", fact: "All clownfish are born male; some change sex to lead a group." },
  { name: "Betta", fact: "Can breathe air with a labyrinth organ — survives in shallow pools." },
  { name: "Anglerfish", fact: "Females use a bioluminescent lure to hunt in the deep sea." },
  { name: "Atlantic Bluefin Tuna", fact: "Can swim over 40 mph and cross entire oceans." },
  { name: "Seahorse", fact: "Males carry eggs in a brood pouch until they hatch." },
  { name: "Pufferfish", fact: "Inflates with water; many species carry a potent toxin." },
  { name: "Mahi-Mahi", fact: "Also called dolphinfish — fast, colorful, and prized for eating." },
  { name: "Channel Catfish", fact: "Taste the world with whisker-like barbels." },
  { name: "Swordfish", fact: "Heats its eyes and brain above water temperature for deep hunting." },
  { name: "Flying Fish", fact: "Glides above the surface using enlarged pectoral fins." },
  { name: "Lionfish", fact: "Invasive in the Gulf — venomous spines, few natural predators." },
  { name: "Tarpon", fact: "Famous for acrobatic leaps — \"silver king\" of coastal flats." },
  { name: "Flounder", fact: "Both eyes migrate to one side as the juvenile settles on the bottom." },
  { name: "Great White Shark", fact: "Can detect a single drop of blood diluted in 25 gallons of water." },
  { name: "Scalloped Hammerhead", fact: "Wide head may improve stereo smell and maneuverability." },
  { name: "Whale Shark", fact: "Largest fish alive — filter-feeder, gentle despite its size." },
  { name: "Bull Shark", fact: "Tolerates fresh water; has been found far up rivers." },
  { name: "Tiger Shark", fact: "Notorious undiscriminating diet — nicknamed \"ocean garbage can.\"" },
  { name: "Nurse Shark", fact: "Often rests piled on the seafloor during the day." },
  { name: "Leopard Shark", fact: "Harmless coastal species with bold saddle-like spots." },
  { name: "Shortfin Mako", fact: "Among the fastest sharks — bursts near 45 mph." },
  { name: "Common Thresher Shark", fact: "Uses its long tail like a whip to herd and stun prey." },
  { name: "Greenland Shark", fact: "May live centuries — among the slowest swimming sharks." },
  { name: "Cookiecutter Shark", fact: "Leaves round plug bites on whales, submarines, and cameras." },
  { name: "Goblin Shark", fact: "Protruding snout and jaw that thrusts forward to snatch prey." },
  { name: "Basking Shark", fact: "Second-largest fish — swims mouth-open filtering plankton." },
  { name: "Sand Tiger Shark", fact: "Looks fierce but is generally sluggish and not very aggressive." },
  { name: "Blue Shark", fact: "Sleek pelagic hunter — one of the most wide-ranging sharks." },
  { name: "Frilled Shark", fact: "Serpentine deep-water species called a \"living fossil.\"" },
  { name: "Epaulette Shark", fact: "Walks on fins in shallow reef pools at low tide." },
  { name: "Horn Shark", fact: "Lays spiral corkscrew eggs wedged into rocky crevices." },
  { name: "Zebra Shark", fact: "Leopard-spotted adult — juveniles have zebra-like stripes." },
  { name: "Port Jackson Shark", fact: "Distinctive harness markings and pig-like grinding teeth." },
  { name: "Blacktip Reef Shark", fact: "Common on coral reefs — often seen in clear shallow water." },
  { name: "Whitetip Reef Shark", fact: "Slim shark that can rest while actively pumping water over gills." },
  { name: "Spotted Wobbegong", fact: "Carpet shark with fringe camouflage — ambush predator." },
  { name: "Longnose Sawshark", fact: "Toothed rostrum sweeps side to side to detect and slash prey." },
  { name: "Spiny Dogfish", fact: "Small shark with a spine in front of each dorsal fin." },
  { name: "Sixgill Shark", fact: "Extra gill slits hint at ancient shark ancestry." },
  { name: "Salmon Shark", fact: "Warm-bodied predator of the North Pacific — related to makos." },
  { name: "Dwarf Lanternshark", fact: "One of the smallest sharks — glows with photophores." },
  { name: "Pygmy Shark", fact: "Bean-sized deep-sea shark that lights up along its belly." },
  { name: "Blobfish", fact: "Gelatinous body collapses into a famous \"sad\" shape out of water." },
  { name: "Stonefish", fact: "World's most venomous fish — camouflaged like a rock." },
  { name: "Fangtooth", fact: "Has the largest teeth relative to body size of any ocean fish." },
  { name: "Barreleye", fact: "Transparent dome on its head shields upward-facing tubular eyes." },
  { name: "Tripod Fish", fact: "Perches on elongated fins on the abyssal plain for hours." },
  { name: "Chimaera", fact: "Ghost shark — cartilaginous relative with a venomous dorsal spine." },
  { name: "Coelacanth", fact: "Thought extinct until rediscovered in 1938 — lobe-finned living fossil." },
  { name: "Giant Oarfish", fact: "Ribbon-like deep giant that may inspire sea-serpent legends." },
  { name: "Ocean Sunfish", fact: "Mola mola — can weigh over a ton and hosts many parasites." },
  { name: "Sarcastic Fringehead", fact: "Opens its huge neon mouth in fierce territorial face-offs." },
  { name: "Northern Stargazer", fact: "Buries in sand and ambushes prey — some species are electric." },
  { name: "Red-lipped Batfish", fact: "Walks on modified fins; lure on its snout attracts prey." },
  { name: "Psychedelic Frogfish", fact: "Tropical ambusher with wild swirling color patterns." },
  { name: "Gulper Eel", fact: "Massive stretchy jaws swallow prey much larger than you'd expect." },
  { name: "Sloane's Viperfish", fact: "Needle teeth and bioluminescent sides in the midnight zone." },
  { name: "Black Dragonfish", fact: "Females glow red; males are tiny and parasitically attach in some species." },
  { name: "Hatchetfish", fact: "Silver sides reflect light to hide silhouette from predators below." },
  { name: "American Paddlefish", fact: "Filter-feeder with a paddle snout — freshwater living fossil." },
  { name: "Arapaima", fact: "Amazon giant that surfaces to gulp air in oxygen-poor waters." },
  { name: "Mudskipper", fact: "Amphibious fish that climbs mangrove roots and breathes air." },
  { name: "Archerfish", fact: "Shoots water jets to knock insects off overhanging plants." },
  { name: "West African Lungfish", fact: "Estivates in mud cocoons during drought — breathes air." },
  { name: "Candy Darter", fact: "Tiny Appalachian fish named for its bright banded colors." },
  { name: "Spotted Handfish", fact: "Walks on hand-like fins on the Tasmanian seafloor — critically rare." },
  { name: "Asian Sheepshead Wrasse", fact: "Develops a bulbous forehead and chin as it matures." },
  { name: "Mandarinfish", fact: "One of few vertebrates with blue pigment from cellular structure." },
  { name: "Ribbon Eel", fact: "Starts black and yellow, may turn blue — dramatic reef dancer." },
  { name: "Garden Eel", fact: "Colonies bob from burrows like seagrass in a current." },
  { name: "Green Moray Eel", fact: "Opens and closes its mouth to pump water over its gills." },
  { name: "Electric Ray", fact: "Can discharge over 200 volts to stun prey or defend itself." },
  { name: "Smalltooth Sawfish", fact: "Rostrum detects prey; critically endangered in U.S. waters." },
  { name: "Hagfish", fact: "Jawless slime ejector — ties knots in its body to escape predators." },
  { name: "Sea Lamprey", fact: "Parasitic disk mouth — invaded Great Lakes and changed ecosystems." },
  { name: "Spotted Ratfish", fact: "Chimaera cousin with rabbit-like teeth and big spotted spots." },
  { name: "Wolf Eel", fact: "Not a true eel — pairs mate for life in Pacific rocky dens." },
  { name: "Pacu", fact: "Amazon relative of piranhas — famous for human-like teeth." },
  { name: "Goliath Tigerfish", fact: "Congo predator with dagger teeth — called the \"demon fish.\"" },
  { name: "Payara", fact: "Vampire fish — two fangs slot into sockets in its upper jaw." },
  { name: "Northern Snakehead", fact: "Invasive air-breather that can travel short distances on land." },
  { name: "Walking Catfish", fact: "Wriggles across wet ground using spiny pectoral fins." },
  { name: "Glass Catfish", fact: "Transparent body — you can see its spine and organs." },
  { name: "Remora", fact: "Suction disc on its head lets it hitch rides on sharks and boats." },
  { name: "Monkfish", fact: "Angler relative — enormous mouth, prized tail meat in markets." },
  { name: "Pacific Spiny Lumpsucker", fact: "Round, adhesive pelvic disk — looks like a swimming raspberry." },
  { name: "Footballfish", fact: "Deep-sea angler with a glowing lure and a head like a gridiron ball." },
  { name: "Flashlight Fish", fact: "Harbors bioluminescent bacteria under its eyes." },
  { name: "Pinecone Fish", fact: "Armored plates and bioluminescent bacteria in its jaw." },
  { name: "Slender Snipe Eel", fact: "Tail may be ten times its body length — beak-like jaws." },
  { name: "Stoplight Loosejaw", fact: "Red bioluminescence — many deep fish cannot see red light." },
  { name: "Pelican Eel", fact: "Huge scoop mouth, tiny body — net-feeds in the deep scattering layer." },
  { name: "Humphead Parrotfish", fact: "Beak fuses coral into sand — can weigh over 100 pounds." },
  { name: "Clown Triggerfish", fact: "Bold polka dots and a trigger spine that locks erect in crevices." },
  { name: "Leafy Seadragon", fact: "Related to seahorses — elaborate leaf-like camouflage appendages." },
  { name: "Weedy Seadragon", fact: "Australian dragon with fluttering fins — males carry bright pink eggs." },
  { name: "Crocodile Icefish", fact: "Antarctic fish with clear blood — lacks oxygen-carrying hemoglobin." },
  { name: "Sturgeon", fact: "Ancient armored fish — caviar comes from their eggs." },
  { name: "Longnose Gar", fact: "Armor scales and a long toothed snout — breathes air with a swim bladder." },
  { name: "Bowfin", fact: "Survived since the dinosaurs — can gulp air and walk short distances." },
  { name: "Sheepshead", fact: "Human-like incisors crush crabs and barnacles on Gulf piers." },
  { name: "Queen Triggerfish", fact: "Can lock its spine erect and grunt when divers approach." },
  { name: "Porcupinefish", fact: "Spines stand erect when inflated — cousin of the pufferfish." },
  { name: "Boxfish", fact: "Rigid box-shaped body secretes toxins when stressed." },
  { name: "Surgeonfish", fact: "Sharp scalpels at tail base — tang family on coral reefs." },
  { name: "Bat Ray", fact: "Winged ray that grinds clams with pavement-like teeth plates." },
  { name: "Manta Ray", fact: "Filter-feeding giant with the largest brain of any fish." },
  { name: "Giant Freshwater Stingray", fact: "Can span over 6 feet — lurks on muddy river bottoms." },
  { name: "Gulper Catfish", fact: "Amazon species with a mouth that swallows fish half its size." },
  { name: "Koi", fact: "Ornamental carp bred for centuries — can live decades." },
  { name: "Oscar", fact: "Intelligent aquarium cichlid that recognizes its keeper." },
  { name: "Discus", fact: "Round Amazon cichlid — fry feed on parents' mucus coating." },
  { name: "Razorfish", fact: "Hides head-down in sea grass — swims in synchronized schools." },
];
